# Generated by Django 5.0.2 on 2024-02-27 10:07

import django.core.validators
import employee_app.util.util
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default=employee_app.util.util.get_uuid_id, editable=False, max_length=150, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(9800000000)])),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('HR MANAGER', 'Human Resource Manager'), ('DEVELOPER', 'Developer')], max_length=255)),
                ('joined_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
