# Generated by Django 5.0.2 on 2024-02-27 10:16

import employee_app.util.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_employee_joined_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.CharField(default=employee_app.util.util.get_uuid_id, editable=False, max_length=150, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('expected_date_completion', models.DateField()),
                ('members', models.ManyToManyField(to='employee_app.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
