# Generated by Django 5.0.2 on 2024-03-05 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 3, 5, 10, 41, 57, 359746, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
